# Generated by Django 4.1.2 on 2022-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=20, null=True, verbose_name='姓名')),
                ('age', models.SmallIntegerField(default=0, null=True, verbose_name='年龄')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], default=0, null=True, verbose_name='姓名')),
                ('class_name', models.IntegerField(db_column='class', null=True, verbose_name='班级')),
                ('description', models.TextField(default='', null=True, verbose_name='个性签名')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'tb_student',
            },
        ),
    ]
