# Generated by Django 4.1.2 on 2022-10-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_create_time_student_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
