# Generated by Django 4.1.2 on 2022-10-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_rename_update_time_student_updated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=128, unique=True)),
                ('student_password', models.CharField(max_length=128)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_realName', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'StudentInfo',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=128, unique=True)),
                ('teacher_password', models.CharField(max_length=128)),
                ('teacher_email', models.EmailField(max_length=254, unique=True)),
                ('teacher_realName', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'TeacherInfo',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
