# Generated by Django 4.1.2 on 2022-11-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_id', models.CharField(max_length=60)),
                ('adm_password', models.CharField(max_length=255)),
                ('adm_name', models.CharField(max_length=255)),
                ('depart', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=25)),
                ('course_name', models.CharField(max_length=255)),
                ('course_intro', models.CharField(blank=True, max_length=520, null=True)),
                ('course_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('course_total', models.IntegerField(blank=True, default=0, null=True)),
                ('course_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='course_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=25)),
                ('material_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=25)),
                ('material_name', models.CharField(max_length=255)),
                ('material_intro', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=30)),
                ('stu_password', models.CharField(max_length=255)),
                ('stu_name', models.CharField(max_length=255)),
                ('depart', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stu_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('teacher_password', models.CharField(max_length=255)),
                ('teacher_name', models.CharField(max_length=255)),
                ('depart', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('material_id', models.CharField(max_length=25)),
            ],
        ),
    ]
